global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1m

receivers:
- name: "telegram"
  telegram_configs:
  - bot_token: "8575941277:AAE3ZIup_3xgmJkzgEk2UG6S6aF94sIowvk"
    chat_id: 338396081
    send_resolved: true
    message: |
          {{ if eq .Status "firing" }}
          ⚠️ ALERT: {{ .CommonLabels.alertname }}
          {{ else }}
          ✅ DONE: {{ .CommonLabels.alertname }}
          {{ end }}

          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}
          Summary: {{ .CommonAnnotations.summary }}
