name: Devops Demo CI/CD

on:
  push:
    path:
      - "docker/**"
      


jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t elendumir/devops-demo:1.0 ./app
        
      - name: Push Docker image
        run: docker push elendumir/devops-demo:1.0

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/devops-demo
            git pull
            docker-compose down
            docker-compose up -d --build


