name: Devops Demo CI/CD

on:
  push:
    branches: [ "main" ]
      


jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:   Build Docker image
        run: docker build -t devops-demo ./app

      - name: Run container
        run: docker run -d -p 5000:5000 devops-demo
  
      - name: Test application 
        run: |
          sleep 5
          curl http://localhost:5000

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/devops-demo
            git pull
            docker-compose down
            docker-compose up -d --build


