name: Terraform Deploy

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: elendumir/devops-demo:${{ github.sha }}

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

     # - name: Debug
     #   run: |
     #     pwd
     #     ls -la

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME ./app

      - name: Tag latest
        run: docker tag $IMAGE_NAME elendumir/devops-demo:latest

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image (sha)
        run: docker push $IMAGE_NAME

      - name: Push Docker image (latest)
        run: docker push elendumir/devops-demo:latest

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="image_name=$IMAGE_NAME"
        working-directory: terraform 

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_name=$IMAGE_NAME"
        working-directory: terraform
