name: Terraform Deploy

on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform 

      - name: Terraform Apply
        run: terraform aplly -auto-approve
        working-directory: terraform
